language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"

# command to install dependencies
install:
- pip install -r requirements.txt

# command to run tests with coverage
script:
- python3 -m unittest discover -s tests -p "*Test.py" -q

# disable email notifications
notifications:
  email: false
